---
name: default
type: docker
kind: pipeline

workspace:
  path: /drone/src

platform:
  os: linux
  arch: arm64

steps:
- name: Build tests
  pull: never
  image: ubuntu-cmake
  commands:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  when:
    event:
    - push
    - pull_request
    - tag
    - merge
- name: Run tests
  pull: never
  image: ubuntu-cmake
  commands:
  - cd build
  - ./itertools-cxx-itertools || exit 1
  when:
    event:
    - push
    - pull_request
    - tag
    - merge
---
kind: signature
hmac: ca984ab7103996116fd839a8fe09f9bf45ab5668e42ac724492c13050ee3be0c

...
