---
name: default
type: docker
kind: pipeline

workspace:
  path: /drone/src

platform:
  os: linux
  arch: arm64

steps:
- name: Build tests
  pull: never
  image: ubuntu-cmake
  commands:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  when:
    event:
    - push
    - pull_request
    - tag
    - merge
- name: Run tests
  pull: never
  image: ubuntu-cmake
  commands:
  - echo '0424e616b590074109646b5f68f906e48c0f126a6e17cc7b87fccd111409cf68  tests/itertools.cxx' | sha256sum -c
  - ./build/itertools-cxx-itertools
  when:
    event:
    - push
    - pull_request
    - tag
    - merge
---
kind: signature
hmac: 6601604d891eba12084dd8206b650e7576937a3219e687e113cc1d1837e45205

...
