---
name: default
type: docker
kind: pipeline

workspace:
  path: /drone/src

platform:
  os: linux

steps:
- name: Build and Run Tests
  pull: never
  image: ubuntu-cmake
  commands:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest
  when:
    event:
    - push
    - tag
    - merge
---
kind: signature
hmac: 74343b3b9bb211c4ae6bb308776dcd61b0ab7795b8120de7eb1ac95480ad5701

...
