---
name: default
type: docker
kind: pipeline

workspace:
  path: /drone/src

platform:
  os: linux
  arch: arm64

steps:
- name: Build tests
  pull: never
  image: ubuntu-cmake
  commands:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  when:
    event:
    - push
    - pull_request
    - tag
    - merge
- name: Run tests
  pull: never
  image: ubuntu-cmake
  commands:
  - echo '5d4d5e7a54bd94e45779c914bff6be4a1c989259c861047f0346053012298441  tests/itertools.cxx' | sha256sum -c
  - ./build/itertools-cxx-itertools
  when:
    event:
    - push
    - pull_request
    - tag
    - merge
---
kind: signature
hmac: 664914fad5e6d0c27ce71ecf3c7c2eabdfd95ffd5e132af5a9b5ff57fd343c9d

...
