when:
  event:
    - push
    - tag
    - pull_request_closed

steps:
  build:
    image: ubuntu-cmake
    commands:
      - mkdir build
      - cd build
      - cmake ..
      - cmake --build .
  test:
    image: ubuntu-cmake
    commands:
      - ctest
