when:
  event:
    - push
    - tag
    - pull_request_closed
    - manual

steps:
  build:
    image: tumbleowlee/c-lang:latest
    commands:
      - mkdir build
      - cd build
      - cmake ..
      - cmake --build .

  test:
    image: tumbleowlee/c-lang:latest
    commands:
      - cd build
      - ctest
