steps:
  build:
    image: ubuntu-cmake
    commands:
      - mkdir build
      - cd build
      - cmake ..
      - cmake --build .
    when:
      event:
        - push
        - tag
        - pull_request_closed
  test:
    image: ubuntu-cmake
    commands:
      - cd build
      - ctest
    when:
      event:
        - push
        - tag
        - pull_request_closed
